export const INITIALIZE_APP_REQUEST = 'INITIALIZE_APP_REQUEST'
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS'
export const INITIALIZE_APP_FAILURE = 'INITIALIZE_APP_FAILURE'

export default {
  INITIALIZE_APP_REQUEST,
  INITIALIZE_APP_SUCCESS,
  INITIALIZE_APP_FAILURE
}
